### ISSUE TITLE
Add possibility to extend snippets to other filetypes

### ISSUE THREAD

**Issue by lambtho12** [L3MON4D3/LuaSnip#161]
With Ultisnips it is possible to create snippets for a specific filetype that builds on snippets existing for an other filetype (using the `extends` command).

A specific example where this is useful is for instance with vimwiki (which uses `vimwiki` filetype instead of regular `markdown`). In that case, it is useful to have specific snippets for vimwiki, but also activate normal markdown snippets.

Is that feature already possible with LuaSnip? Would that be possible to add it?

**Comment by L3MON4D3** [comment]
Would either of #132 or #142 work for you?

**Comment by lambtho12** [comment]
From #132, I tried that
```lua
require("luasnip").snippets={
  vimwiki ={}
}
require("luasnip").snippets.vimwiki = require("luasnip").snippets.markdown
require("luasnip/loaders/from_vscode").load({include = {"markdown"}})
require("luasnip/loaders/from_vscode").lazy_load()
```
but it does not seem to work. Not sure if #142 applies here as it is a completely different filetype and not just something like `md.vimwiki`

**Comment by L3MON4D3** [comment]
#132 should work if you do
```lua
require("luasnip").snippets.markdown = require("luasnip").snippets.vimwiki
```
instead, it's all about using the same table for `vimwiki` and `markdown` snippets.

You can make #142 work by manually setting `ft` to `markdown.vimwiki`(via autocmd or `after/ftplugin/vimwiki.vim`), but that may interfere with other plugins.

Both are rather hacky, so I'd also be open to support something like `extend` from Ultisnips.

**Comment by lambtho12** [comment]
Indeed that kinda work if I write it in the correct way 😄 

But now if I write my snippets for vimwiki as 
```lua
require("luasnip").snippets={
  vimwiki ={
    s("test1", {
      t("this is my awesome text snippet")
    }),
  }
}
```

the snippets are also going to be present when I edit simple markdown files. Would it be possible to avoid that and have these extra snippets only work for vimwiki?

**Comment by L3MON4D3** [comment]
That's the hackiness :P
I'll add the `extend`, that should make it work properly.
How does it work in ultisnips? Just `extend(filetype, with_this_filetype)`?

**Comment by L3MON4D3** [comment]
Check out the proper_filetype_extend-branch,
```lua
require("luasnip").filetype_extend("vimwiki", "markdown")
```
should work.

**Comment by lambtho12** [comment]
Does not seems to work.
I have the following error when neovim starts:
```
Error detected while processing /home/lambtho/.dotfiles/nvim/.config/nvim/init.lua:
E5113: Error while calling lua chunk: vim/shared.lua:320: src: expected table, got string
stack traceback:
        vim/shared.lua:320: in function 'list_extend'
        ...nvim/site/pack/packer/start/LuaSnip/lua/luasnip/init.lua:377: in function 'filetype
_extend'
        /home/lambtho/.config/nvim/init.lua:32: in main chunk
```

**Comment by lambtho12** [comment]
Error is fixed when using 
```require("luasnip").filetype_extend({"vimwiki"}, {"markdown"})``

Although it still does not work. I get mardown snippets in markdown, vimwiki specific snippets in vimwiki but no markdown in vimwiki.

My config is
```
require("luasnip").snippets={
  vimwiki ={
    s("test1", {
      t("this is my awesome text snippet")
    }),
  }
}

require("luasnip").filetype_extend({"vimwiki"}, {"markdown"})
require("luasnip/loaders/from_vscode").lazy_load()
```

**Comment by L3MON4D3** [comment]
Could you try
```lua
luasnip.filetype_extend("vimwiki", {"markdown"})
```

**Comment by lambtho12** [comment]
> Could you try
> 
> ```lua
> luasnip.filetype_extend("vimwiki", {"markdown"})
> ```

No neovim error, but still not working as expected (i.e. markdown snippets in markdown, vimwiki specific snippets in vimwiki but no markdown snippets in vimwiki).

**Comment by saadparwaiz1** [comment]
A bit off topic but here's how I accomplish this.

### Main LuaSnip Config
```lua
setmetatable(require('luasnip').snippets, {
   __index = function(_, v)
       return require('snippets.' .. v)
   end
})
```

### markdown.lua in lua/snippets directory
```lua
return {
  -- snippets here
}
```

### vimwiki.lua in lua/snippets directory
```lua
local markdown_snippets = require('snippets.markdown')
-- add custom snippets
return markdown_snippets
```

**Comment by saadparwaiz1** [comment]
> Almost there.. 😄
> 
> In markdown: it is working as expected, but all markdown snippets appear twice in nvim-cmp.
> In vimwiki: Vimwiki snippets appear once in nvim-cmp, markdown snippets work but do not show in nvim-cmp
> 
> although, maybe this should be fixed in https://github.com/saadparwaiz1/cmp_luasnip

@lambtho12 can you try out this [pr](https://github.com/saadparwaiz1/cmp_luasnip/pull/10#issue-731926627) it should fix the nvim-cmp issue

**Comment by lambtho12** [comment]
Ok. I will report on the tests [on the PR](https://github.com/saadparwaiz1/cmp_luasnip/pull/10#issue-731926627) directly to keep things separate

**Comment by L3MON4D3** [comment]
> > Almost there.. 😄
> > In markdown: it is working as expected, but all markdown snippets appear twice in nvim-cmp.
> > In vimwiki: Vimwiki snippets appear once in nvim-cmp, markdown snippets work but do not show in nvim-cmp
> > although, maybe this should be fixed in https://github.com/saadparwaiz1/cmp_luasnip
> 
> @lambtho12 can you try out this [pr](https://github.com/saadparwaiz1/cmp_luasnip/pull/10#issue-731926627) it should fix the nvim-cmp issue

Ha, beat me to it :D

**Comment by lambtho12** [comment]
Finally, it seems that there is still an issue... Not sure if it is from here or cmp_luasnip.
As explained on [cmp_luasnip](https://github.com/saadparwaiz1/cmp_luasnip/pull/10#issuecomment-917408591), when I want to use a snippet in vimwiki, I get the following 
```
E5108: Error executing lua .../pack/packer/start/LuaSnip/lua/luasnip/nodes/snippet.lua:774: Vi
m:E492: Not an editor command: VimtexEventInitPost call vimtex#syntax#core#init_post()
```
(and I really do not know why it references [vimtex](https://github.com/lervag/vimtex) here...)

**Comment by L3MON4D3** [comment]
Seems like it happens while running the autocommands for snippet events, do you have an autocommand on them?

**Comment by lambtho12** [comment]
These are the only autocommand I have:
```
local cmd = vim.cmd
cmd 'au TextYankPost * lua vim.highlight.on_yank {on_visual = false}'  -- disabled in visual mode
cmd 'autocmd BufRead,BufNewFile *.tex,*.dtx,*.md setlocal textwidth=80'
cmd 'autocmd FileType beancount,tex,markdown autocmd BufWritePre <buffer> %s/\\s\\+$//e'
```

**Comment by L3MON4D3** [comment]
Hmmm, weird.. 
Did you expand the snippet via nvim_cmp or directly via trigger?

**Comment by lambtho12** [comment]
Same thing if I expand it by nvim_cmp or via direct trigger. In any case, the snippet expand, but I still get the error message.
If I expand it by pressing <CR> on the nvim_cmp menu, it breaks nvim_cmp menu and it will not show it anymore after that (in any buffer). If I close the cmp menu and expand the snippet via direct trigger, the cmp menu continues working

**Comment by L3MON4D3** [comment]
Did the reinstall you mentioned in nvim_cmp also fix this error?

**Comment by lambtho12** [comment]
Yes! Sorry, I forgot to mention it here as well.
I still have no idea about what was the underlying issue.

**Comment by L3MON4D3** [comment]
Nice :ok_hand:
Soooo... everything works? :eyes: :P

**Comment by lambtho12** [comment]
I haven't written much yet, but it seems to be good for now. Thank you again for your quick solution.
I will reopen this issue if I stumble across an issue with a bit more use.

**Comment by gegoune** [comment]
Apologies for digging this out, thought it might be more fitting than crating new issue but can do that if you prefer it that way.

friendly-snippets just merged conventional commit snippets (for git). I am trying to get them to work with Neogit, which sets its own filetype instead of `gitcommit`. I am lazy loading snippets like this (I have no lazy loading of any plugins, etc):

```lua
local ls = require 'luasnip'
require('luasnip.loaders.from_vscode').lazy_load {}
ls.filetype_extend('NeogitCommitMessage', { 'gitcommit' })
```

but it does not show those snippets. It works when I use `load()` instead of `lazy_load()`. Is that expected or an issue? Would rather not load all snippets (continue using `lazy_load()`).

**Comment by L3MON4D3** [comment]
Weird, I cannot reproduce :/
```vim
" don't have Neogit, so try this
:!echo "vim: ft=NeogitCommitMessage" > ngcm
:lua ls.filetype_extend("NeogitCommmitMessage", {"gitcommit"})
:lua require("luasnip.loaders.from_vscode").lazy_load()
:e ngcm
feat<Tab> expands
```
(I'm not on the most current version of `friendly-snippets` where this specific issue is fixed)

We load snippets on `BufEnter`, so if the correct filetype isn't set by then, it fails. Can you verify that it works with explicitly setting the filetype and doesn't with actual `Neogit`?

**Comment by gegoune** [comment]
I tried what you did above but it still doesn't show nor expand those snippets.
